/** Workspace module constants */
export const WORKSPACE = {
  TYPE: {
    PERSONAL: 'personal',
    ORGANIZATION: 'organization',
  },
  MODE: {
    SINGLE: 'single',
    MULTIPLE: 'multiple',
  },
  ERRORS: {
    NOT_FOUND: 'Workspace not found',
    NOT_OWNER: 'Only workspace owner can perform this action',
    NOT_MEMBER: 'You are not a member of this workspace',
    CANNOT_DELETE_PERSONAL: 'Personal workspace cannot be deleted',
    SLUG_CONFLICT: 'Workspace slug already exists',
    WORKSPACE_REQUIRED: 'Workspace ID is required',
    SELF_SERVICE_DISABLED: 'Workspace creation is invitation-only',
    PERSONAL_EXISTS: 'Personal workspace already exists',
    CANNOT_REMOVE_OWNER: 'Cannot remove workspace owner',
    CANNOT_REMOVE_SELF: 'Cannot remove yourself from workspace',
    CANNOT_CHANGE_OWNER_ROLE: 'Cannot change workspace owner role',
    CANNOT_CHANGE_OWN_ROLE: 'Cannot change your own role',
    CANNOT_ASSIGN_OWNER: 'Cannot assign owner role via API',
    MEMBER_NOT_FOUND: 'Member not found in workspace',
    INVITATION_NOT_FOUND: 'Invitation not found',
    INSUFFICIENT_ROLE: 'Insufficient permissions for this action',
  },
  MESSAGES: {
    CREATED: 'Workspace created',
    UPDATED: 'Workspace updated',
    DELETED: 'Workspace deleted',
    LIST: 'Workspaces retrieved',
    DETAIL: 'Workspace retrieved',
    SWITCHED: 'Workspace switched',
    MEMBERS_LIST: 'Members retrieved',
    ROLE_UPDATED: 'Member role updated',
    MEMBER_REMOVED: 'Member removed',
    INVITATIONS_LIST: 'Invitations retrieved',
    INVITATION_REVOKED: 'Invitation revoked',
  },
  ERROR_CODE: 'WORKSPACE_ERROR',
} as const;
