import {
  faArrowDown,
  faArrowRightFromBracket,
  faArrowsRotate,
  faArrowUp,
  faArrowsUpDown,
  faArrowUpRightFromSquare,
  faBan,
  faBook,
  faBrain,
  faBug,
  faCalendarDays,
  faCamera,
  faChartBar,
  faCheck,
  faChevronDown,
  faCircleCheck,
  faCircleInfo,
  faClipboardCheck,
  faClock,
  faClockRotateLeft,
  faCodeBranch,
  faCopy,
  faDatabase,
  faDiagramProject,
  faDownload,
  faEllipsisVertical,
  faEnvelope,
  faEnvelopeOpenText,
  faExclamationTriangle,
  faEye,
  faFileCode,
  faFileLines,
  faFlask,
  faFlaskVial,
  faFloppyDisk,
  faFolderOpen,
  faFolderPlus,
  faGear,
  faKey,
  faKeyboard,
  faLightbulb,
  faLink,
  faLinkSlash,
  faList,
  faLock,
  faMagnifyingGlass,
  faMicroscope,
  faPaperPlane,
  faPause,
  faPen,
  faPenToSquare,
  faPeopleGroup,
  faPlay,
  faPlug,
  faPlus,
  faRobot,
  faRotate,
  faRotateRight,
  faSatelliteDish,
  faShieldHalved,
  faTableCellsLarge,
  faTimeline,
  faToggleOff,
  faToggleOn,
  faTrash,
  faTriangleExclamation,
  faUser,
  faUserPlus,
  faUsers,
  faUsersGear,
  faUserShield,
  faUserSlash,
  faVolumeXmark,
  faXmark,
  faCodeFork,
} from '@fortawesome/free-solid-svg-icons'

import {
  faGithub,
  faGitlab,
} from '@fortawesome/free-brands-svg-icons'

import { type IconDefinition } from '@fortawesome/fontawesome-svg-core'

export const iconMap: Record<string, IconDefinition> = {
  'arrow-down': faArrowDown,
  'arrow-right-from-bracket': faArrowRightFromBracket,
  'arrows-rotate': faArrowsRotate,
  'arrow-up': faArrowUp,
  'arrow-up-arrow-down': faArrowsUpDown,
  'arrow-up-right-from-square': faArrowUpRightFromSquare,
  'ban': faBan,
  'book': faBook,
  'brain': faBrain,
  'bug': faBug,
  'calendar-days': faCalendarDays,
  'camera': faCamera,
  'chart-bar': faChartBar,
  'check': faCheck,
  'chevron-down': faChevronDown,
  'circle-check': faCircleCheck,
  'circle-info': faCircleInfo,
  'clipboard-check': faClipboardCheck,
  'clock': faClock,
  'clock-rotate-left': faClockRotateLeft,
  'code-branch': faCodeBranch,
  'copy': faCopy,
  'database': faDatabase,
  'diagram-project': faDiagramProject,
  'download': faDownload,
  'ellipsis-vertical': faEllipsisVertical,
  'envelope': faEnvelope,
  'envelope-open-text': faEnvelopeOpenText,
  'exclamation-triangle': faExclamationTriangle,
  'eye': faEye,
  'file-code': faFileCode,
  'file-lines': faFileLines,
  'flask': faFlask,
  'flask-vial': faFlaskVial,
  'floppy-disk': faFloppyDisk,
  'folder-open': faFolderOpen,
  'folder-plus': faFolderPlus,
  'gear': faGear,
  'key': faKey,
  'keyboard': faKeyboard,
  'lightbulb': faLightbulb,
  'link': faLink,
  'link-slash': faLinkSlash,
  'list': faList,
  'lock': faLock,
  'magnifying-glass': faMagnifyingGlass,
  'microscope': faMicroscope,
  'paper-plane': faPaperPlane,
  'pause': faPause,
  'pen': faPen,
  'pen-to-square': faPenToSquare,
  'people-group': faPeopleGroup,
  'play': faPlay,
  'plug': faPlug,
  'plus': faPlus,
  'robot': faRobot,
  'rotate': faRotate,
  'rotate-right': faRotateRight,
  'satellite-dish': faSatelliteDish,
  'shield-halved': faShieldHalved,
  'table-cells-large': faTableCellsLarge,
  'timeline': faTimeline,
  'toggle-off': faToggleOff,
  'toggle-on': faToggleOn,
  'trash': faTrash,
  'triangle-exclamation': faTriangleExclamation,
  'user': faUser,
  'user-plus': faUserPlus,
  'users': faUsers,
  'users-gear': faUsersGear,
  'user-shield': faUserShield,
  'user-slash': faUserSlash,
  'volume-xmark': faVolumeXmark,
  'xmark': faXmark,
  'solid fa-code-fork': faCodeFork,
  'brands fa-github': faGithub,
  'brands fa-gitlab': faGitlab,
}
